I created multiple models but photos are not displayed
westbee/ember-learn-project pull request #4
Opened 2018-11-14 11:03 UTC by westbee

According to your requirements, I created multiple models and used a dynamic segment to load a proper gallery model. Now I need a hint on how I can display photos in a gallery because it looks like something is missing when two models are present in the same gallery page.

2018-11-19 14:12 UTC, patsy-issa requested changes
All around good job 👍

2018-11-19 14:12 UTC, patsy-issa commented on app/models/gallery.js
> +  photo: DS.hasMany('photo', { inverse: 'gallery' })
`photos: DS.hasMany('photo')`
When defining a `hasMany` relationship use the plural form for the key name and there is no need to specify inverse here ^^

2018-11-19 14:12 UTC, Patsy-issa commented on app/models/photo.js
> +  categoryId: DS.attr('number'),
`category` looks like a good candidate for a model, this way you can define it as a `belongsTo` and leverage ember data for querying ^^

2018-11-19 14:12 UTC, Patsy-issa commented on app/router.js
> +  // });
Generally removing unused/commented out code makes for a cleaner code base.

2018-11-19 14:12 UTC, Patsy-issa commented on app/routes/galleries/kinder-familien.js
> +});
This file is not needed.

2018-11-19 14:12 UTC, Patsy-issa commented on app/routes/galleries/neugeborene-babybauch.js
> +});
This file is not needed.

2018-11-19 14:12 UTC, Patsy-issa commented on app/routes/galleries/portraitphotographie.js
> +});
This file is not needed.

2018-11-19 14:12 UTC, Patsy-issa commented on app/templates/galleries/index.hbs
> +			{{/each}} -->
Remove the commented out code.

2018-11-19 14:12 UTC, Patsy-issa commented on app/templates/index.hbs
> +        </div>
Is this part still needed? It is defined in `galleries.index`

2018-11-19 14:12 UTC, Patsy-issa commented on app/routes/application.js
> +    });
Are all galleries and all their photos displayed in the application template? If not you can get a specific galleries' photos from `gallery.photos`.

2018-11-19 14:58 UTC, pangratz reviewed
There is no linkage between gallery <-> photos in your mirage setup, so I guess that's why no photos are displayed.

2018-11-19 14:58 UTC, pangratz commented on config/environment.js
> +  'use strict';
No biggie, but this change is not relevant.

I am using `git add --patch` to interactively add hunks to the staging area. This basically allows you to review and tell `git` which changes should be added and committed later.

2018-11-19 14:58 UTC, pangratz commented on mirage/config.js
> +  this.get('/galleries/:gallery_id');
This needs to be `this.get('/galleries/:id');` in order for mirage to automatically return the gallery with the given id, see http://www.ember-cli-mirage.com/docs/v0.4.x/route-handlers/#shorthands.

Otherwise this needs to be something along the lines of:

```js
this.get('/galleries/:gallery_id', function({ galleries }, request) {
  return galleries.find(request.params.gallery_id);0
});
```

2018-11-19 14:58 UTC, pangratz commented on app/controllers/galleries/gallery.js
> +  mappedModel: map('model', function(item) {
`map` expects the `model` to be an array, but it is actually a single `gallery`. Once the `photos` are connected correctly to a gallery, changing this to `model.photos` should work here.

Also, I would rename this property from `mappedModel` to something more expressive like `mappedPhotos` or so.

2018-11-20 11:31 UTC, westbee commented on app/templates/index.hbs
> +        </div>
This part should be also here on the main page.

2018-11-23 11:39 UTC, westbee commented on app/templates/index.hbs
> +        </div>
I built a category-list component, so I can re-use this part anywhere.

2018-11-26 09:17 UTC, westbee commented
The photos are displayed and filtered in each gallery, but the console shows now an error "Mirage: Your GET handler for the url /api/galleries/1 threw an error: Cannot read property 'all' of undefined".

2018-11-27 09:45 UTC, closed without merging